<?php

use common\models\siteobject\SiteObjectSeo;
use dmstr\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\widgets\DetailView;

/** @var SiteObjectSeo */
$seoObject = $model->seoObject;
?>

<div class="site-object-seo-form">
<?php echo DetailView::widget([
		'model' => $seoObject,
		'attributes' => [
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
			'heading',
			'title:ntext',
			'description:ntext',
			'keywords',
			'text1:ntext',
			'text2:ntext',
			// 'text3:ntext',
			'pagination_title:ntext',
			'pagination_description:ntext',
			'pagination_keywords',
		],
	]); ?>

</div>
<style>
    .site-object-seo-form th {
        width: 15%;
    }
</style>