<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\siteobject;

use Yii;

/**
 * This is the base-model class for table "site_object".
 *
 * @property integer $id
 * @property string $table_name
 * @property integer $row_id
 *
 * @property \common\models\siteobject\SiteObjectMediaTarget[] $siteObjectMediaTargets
 * @property \common\models\siteobject\SiteObjectSeo[] $siteObjectSeos
 * @property string $aliasModel
 */
class SiteObject extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'site_object';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['row_id'], 'integer'],
            [['table_name'], 'string', 'max' => 255],
            [['table_name', 'row_id'], 'unique', 'targetAttribute' => ['table_name', 'row_id']],
            [['table_name', 'row_id'], 'required']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'table_name' => Yii::t('models', 'Table Name'),
            'row_id' => Yii::t('models', 'Row ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSiteObjectMediaTargets()
    {
        return $this->hasMany(\common\models\siteobject\SiteObjectMediaTarget::className(), ['site_object_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSiteObjectSeos()
    {
        return $this->hasMany(\common\models\siteobject\SiteObjectSeo::className(), ['site_object_id' => 'id']);
    }

    public function beforeDelete()
    {
        $objectsToClean = array_merge($this->siteObjectMediaTargets, $this->siteObjectSeos);
        foreach ($objectsToClean as $object) {
            if (!$object->delete()) {
                return false;
            }
        }

        return parent::beforeDelete();
    }
}
