<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\blog;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the base-model class for table "blog_post_tag".
 *
 * @property integer $blog_post_id
 * @property integer $blog_tag_id
 * @property integer $sort
 *
 * @property \common\models\blog\BlogPost $blogPost
 * @property \common\models\blog\BlogTag $blogTag
 * @property string $aliasModel
 */

class BlogPostTag extends \yii\db\ActiveRecord
{

    use \common\utility\SortableTrait;
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return
            ArrayHelper::merge(
                [],
                $this->sortableModelBehavior()
            );
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'blog_post_tag';
    }

    public static function primaryKey()
    {
        return ['blog_post_id', 'blog_tag_id'];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['blog_post_id', 'blog_tag_id', 'sort'], 'integer'],
            [['blog_post_id', 'blog_tag_id'], 'unique', 'targetAttribute' => ['blog_post_id', 'blog_tag_id']],
            [['blog_post_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\blog\BlogPost::className(), 'targetAttribute' => ['blog_post_id' => 'id']],
            [['blog_tag_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\blog\BlogTag::className(), 'targetAttribute' => ['blog_tag_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'blog_post_id' => Yii::t('models', 'Blog Post ID'),
            'blog_tag_id' => Yii::t('models', 'Blog Tag ID'),
            'sort' => Yii::t('models', 'Sort'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBlogPost()
    {
        return $this->hasOne(\common\models\blog\BlogPost::className(), ['id' => 'blog_post_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBlogTag()
    {
        return $this->hasOne(\common\models\blog\BlogTag::className(), ['id' => 'blog_tag_id']);
    }

}
